config/routes.rb
Rails.application.routes.draw do
  root 'parks#index'
  devise_for :users
    resources :parks, only: [:index, :new, :create, :show, :edit, :update, :destroy]do
    resources :reviews, only: [:new, :create, :edit, :update, :destroy]
  end


  namespace :api do
    namespace :v1 do
      resources :parks, only: [:index, :show]
      resources :reviews, only: [:index, :new, :create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/park.rb
class Park < ApplicationRecord
  mount_uploader :park_photo, ParkPhotoUploader

  validates :name, presence: true
  validates :address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip, presence: true
  validates :description, presence: true
  has_many :reviews
end

app/models/review.rb
class Review < ApplicationRecord
  validates :rating, presence: true, inclusion: { in: [1,2,3,4,5] }
  validates :body, presence: true
  validates :park_id, presence: true
  validates :user_id, presence: true

  belongs_to :park
  belongs_to :user
  has_many :votes 
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews
  has_many :votes
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  def admin?
    role == "admin"
  end
end

app/models/vote.rb
class Vote <ApplicationRecord
  belongs_to :user
  belongs_to :review

  validates: user_id, presence: true
  validates: review_id, presence: true
  validates: vote_type, presence: true, inclusion: {in: ['thumbs_up', 'thumbs_down']}
end

app/controllers/api/v1/parks_controller.rb
class Api::V1::ParksController < ApplicationController
  def index
    render json: {
    parks: ActiveModel::Serializer::CollectionSerializer.new(Park.all, each_serializer: ParkSerializer),
    reviews: ActiveModel::Serializer::CollectionSerializer.new(Review.all, each_serializer: ReviewSerializer)
    }
  end

  def show
   park = Park.find(params[:id])
   render json: park
  end

  # def update
  #   park = Park.find(params[:park_id])
  #   review= Review.find(params[:review_id])
  #
  #   vote = Vote.new(vote_params)
  #   if vote.save
  #     flash[:success] = "Vote added successfully"
  #     redirect_to @park
  #   else
  #     flash.now[:error] = vote.errors.full_messages.join(",")
  #   end
  # end
  #
  # def vote_params
  #   params.requre(:vote).permit(:user_id, :review_id, :vote_type)
  # end
  #
  # def vote_params
  #   params.requre(:vote).permit(:user_id, :review_id, :vote_type)
  # end
end

app/controllers/api/v1/reviews_controller.rb
class Api::V1::ReviewsController < ApplicationController
def index
  render json: Review.all
end

def new
  @park = Park.find(params[:park_id])
  render json: Review.new
end

def create
  @review = Review.new(review_params)
  @park = Park.find(params[:park_id])
  @review.park = @park
  @review.user_id = current_user.id

  if review.save
    render json: review
  else
    render json: {error.review.errors.full_messages}
  end
end

private

def review_params
  params.require(:review).permit(:rating, :body)
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery unless: -> { request.format.json? }

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :park_photo])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/parks_controller.rb
class ParksController < ApplicationController
  before_action :authorize_user, except: [:index, :show]

  def index
    @parks = Park.all.order("created_at DESC")
  end

  def new
    @park = Park.new
  end

  def create
    @park = Park.new(park_params)

    if @park.save
      flash[:success] = "Dog Park saved successfully"
      redirect_to parks_url
    else
      flash.now[:error] = @park.errors.full_messages.join("<br/>").html_safe
      render :new
    end
  end

  def show
    @park = Park.find(params[:id])
  end

  def edit
    @park = Park.find(params[:id])
  end

  def update
    @park = Park.find(params[:id])

    if @park.update(park_params)
      flash[:success] = "Dog Park edited successfully"
      redirect_to park_path(@park)
    else
      flash.now[:error] = @park.errors.full_messages.join("<br/>").html_safe
      render :edit
    end
  end

  def destroy
    @park = Park.find(params[:id])
    @park.destroy
    flash[:success] = "Dog Park deleted successfully"
    redirect_to parks_path
  end

  private
  def park_params
      params.require(:park).permit(:name, :address, :city, :state, :zip, :description, :park_photo)
  end

  def authorize_user
    if !user_signed_in? || !current_user.admin?
      flash[:notice] = "You do not have access to this page."
      redirect_to root_path
    end
  end
end

app/controllers/review_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
    @park = Park.find(params[:park_id])
  end

  def create
    @review = Review.new(review_params)
    @park = Park.find(params[:park_id])
    @review.park = @park
    if @review.save
      flash[:notice] = "Review add successfully"
      redirect_to @park 
    else
      flash[:notice] = @review.error.full_messages.join(", ")
      render :new
  end

  private

  def review_params
    params.require(:review).permit(:rating, :body)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @reviews = Review.all.order("created_at DESC")
  end

  def new
    @park = Park.find(params[:park_id])
    @review = Review.new
  end

  def edit
    @park = Park.find(params[:park_id])
    @review = Review.find(params[:id])
    unless current_user == @review.user
   redirect_to(@park, notice: "You cannot edit this review") and return
    end
  end

  def update
    @park = Park.find(params[:park_id])
    @review = Review.find(params[:id])
    if @review.update(review_params)
      flash[:success] = "Review edited successfully"
      redirect_to park_path(@park)
    else
      errors = @review.errors.full_messages
      index = errors.index("Rating is not included in the list")
        if (index != nil)
          errors[index] = "Rating must be a number of 1-5"
          errors[index+1] = "Review can't be blank"
        end
      flash.now[:error] = errors.join("<br/>").html_safe
      render :edit
    end
  end

  def destroy
    @park = Park.find(params[:park_id])
    @review = Review.find(params[:id])

    @review.destroy
    flash[:success] = "Review deleted successfully"
    redirect_to park_path(@park)
  end

  def create
    @review = Review.new(review_params)
    @park = Park.find(params[:park_id])
    @review.user_id = current_user.id if current_user
    @review.park = @park
      if @review.save
        flash[:success] = "Review added successfully"
        redirect_to @park
      else
        errors = @review.errors.full_messages
        index = errors.index("Rating is not included in the list")
          if (index != nil)
            errors[index] = "Rating must be a number of 1-5"
            errors[index+1] = "Review can't be blank"
          end
        flash.now[:error] = errors.join("<br/>").html_safe
        render :new
      end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :body)
  end
end

app/controllers/votes_controller.rb
class VotesController <ApplicationController
  def update
    vote = Vote.new(vote_params)
    if vote.save
      flash[:success] = "Vote added successfully"
      redirect_to @park
    else
      flash.now[:error] = vote.errors.full_messages.join(",")
    end
  end

  def vote_params
    params.requre(:vote).permit(:user_id, :review_id, :vote_type)
  end
end

app/views/homes/index.html.erb
<div id="app">
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>DogParkProject</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">


  <%= csrf_meta_tags %>
</head>
<body class="body">
<div class="contain-to-grid full-top-bar">
  <div class="top-bar">
    <div class="top-bar-left">
      <div class="logo">
        <%= link_to image_tag("/logo/doglogo.png"), "/" %>
      </div>
    </div>

    <section class="top-bar-section logo">
      <div class="input-group searchbar">
        <input class="input-field search-field" type="search" placeholder="Search for anything..." />
      </div>
      <div class="right">
        <%- if current_user -%>
          <div class="top-bar-right"><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></div>
        <%- else -%>
        <%= link_to 'Sign Up', new_user_registration_path %> / <%= link_to 'Sign In', new_user_session_path %>
        <%- end -%>
      </div>
    </section>
  </div>
</div>
  <%- flash.each do |key, value| -%>
    <div class="flash flash-<%= key %>">
      <%= value %>
    </div>
  <%- end -%>

      <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

  <%= yield %>

  <%= javascript_include_tag 'application' %>

  <%- if Rails.env.development? || Rails.env.test? -%>
    <%= javascript_tag do %>
      window.railsEnv = '<%= Rails.env %>'
    <%- end -%>
  <%- end -%>
  <%= javascript_pack_tag 'application' %>

  <%= yield :extra_footer %>
</body>
</html>

app/views/parks/edit.html.erb
<center>
<div class="user-box">
<h1> Edit </h1>
<%= form_for @park do |f| %>

  <b><%= f.label :name%></b>
  <%= f.text_field :name%>

  <b><%= f.label :address, "Street Address"%></b>
  <%= f.text_field :address%>

  <b><%= f.label :city%></b>
  <%= f.text_field :city%>

  <b><%= f.label :state%></b>
  <%= f.text_field :state%>

  <b><%= f.label :zip%></b>
  <%= f.text_field :zip%>

  <b><%= f.label :description%></b>
  <%= f.text_field :description%>

  <%= f.submit "Edit Park", :method => :post %><br><br>

  <%= link_to "Delete", park_path(@park), method: :delete, data: {confirm: 'Are you sure?'} %><br><br>

  <%= link_to "Back to Park", park_path %>
<% end %>
</center>
</div>

app/views/parks/index.html.erb
<div class="parkShow">
  <h3 class="hollow button right"><%= link_to "Add a New Park", new_park_path %> </h3>
  <hr class="indexbar"/>
  <ul class="wrapper">

    <% @parks.each do |park|%>
    <a href="/parks/<%= park.id %>">
    <li>
      <div class="callout parktile">
      <div class="callout-header">
        <%= park.name %></div>
    <div class="address">
    <%= park.address %>,
    <%= park.city %>,
    <%= park.state %>
    <div class="photo">
    <%= image_tag park.park_photo.url.to_s %>
    </div>

    </div>
    </li></a>
    <% end %>
  </ul>
</div>

app/views/parks/new.html.erb
<center>
<div class="user-box">
<h1 class="field">New Park Form</h1>
<div class="field">
  <%= form_for(@park) do |f| %>

    <b><%= f.label :name%></b>
    <%= f.text_field :name%>

    <b><%= f.label :address, "Street Address"%></b>
    <%= f.text_field :address%>

    <b><%= f.label :city%></b>
    <%= f.text_field :city%>

    <b><%= f.label :state%></b>
    <%= f.text_field :state%>

    <b><%= f.label :zip%></b>
    <%= f.text_field :zip%>

    <b><%= f.label :description%></b>
    <%= f.text_field :description%>

    <%= f.file_field :park_photo %>
    <%= f.submit "Add Dog Park" %><br><br>

    <%= link_to "Back to Homepage", parks_path %>
  <% end %>
</div>
</center>
</div>

app/views/parks/show.html.erb
<div class="wrapper">

<div id="app">

</div>
<div class="pad">
<% if @park.park_photo? %>
<%= image_tag @park.park_photo.url %>
<% end %>
</div>
</div>

app/views/reviews/edit.html.erb
<center>
<div class="user-box">
<h1>Edit Review</h1>
<div class="field">
<%= form_for([@park, @review]) do |f| %>

  <b><%= f.label :rating%></b>
  <%= f.text_field :rating%>

  <b><%= f.label :body, "Review"%></b>
  <%= f.text_field :body%>

  <%= f.submit "Edit Review" %>

<% end %>
<%= button_to "Delete", park_review_path, method: :delete, data: {confirm: 'Are you sure?'} %><br><br>
<%= button_to "Back to #{@park.name}", park_path(@park), :method => :get %>
</div>
</center>
</div>

app/views/reviews/new.html.erb
<center>
<div class="user-box">
<h1 class="field"> Add Review Form </h1>
<div class="field">
<%= form_for([@park, @review]) do |f| %>

  <b><%= f.label :rating%></b>
  <%= f.text_field :rating%>

  <b><%= f.label :body, "Review"%></b>
  <%= f.text_field :body%>


  <%= f.submit "Add Review" %>

<% end %>

<%= button_to "Back to #{@park.name}", park_path(@park), :method => :get  %>
</div>
</center>
</div>